- name: create a cloudformation stack
  cloudformation:
    stack_name: "ansible-cloudformation"
    state: "present"
    region: "us-east-1"
    disable_rollback: true
    template: "../files/stack.json"
    template_parameters:
      KeyName: "vamshi"       
      InstanceType: "t2.micro"      
    tags:
      Stack: "ansible-cloudformation"

- name: delete a cloudformation stack
  cloudformation:
    stack_name: "ansible-cloudformation"
    state: "absent"